
title: ksoo ì˜ blog
email: hsnks100@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/prob_stats" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site

github_username:  hsnks100





source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Conversion
markdown:    kramdown
lsi:         false
excerpt_separator: "\n\n"

# Markdown Processors
kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     2..3
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter: rouge


highlighter: rouge
