
title: ksoo ì˜ blog
email: hsnks100@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/prob_stats" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site

github_username:  hsnks100

# Build settings
#markdown: kramdown
#theme: minima


# Sass
sass:
  style: :compressed
  sass_dir: css


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
